### ISSUE TITLE
ytdl-desktop

### ISSUE THREAD

**Issue by 93null** [93null/ytdl-desktop#1]
# Problem
Wanna download youtube videos and audio.

# Solution
Make an app lol

# Features
* Search
* Download

That's it. That's the app.

# Tasks

- [ ] Create frontend ui
  - [ ] request manager
  - [ ] Search bar
  - [ ] Results + download buttons
  - [ ] Download manager

- [ ] Create backend functions
  - [ ] (query) -> list of results
  - [ ] (video/playlist url, parameters) -> begin download
  - [ ] (download)-> cancel download

**Comment by 93null** [comment]
# Getting Youtube results with HTTP requests

URL: https://www.youtube.com/results?search_query={ }

Regex for `<script ...> var ytInitialData = { ... } </script>`: `<script[^>]*>var ytI[^<]*<\/script>`

`contents` (roughly):
````json
"contents": {
        "twoColumnSearchResultsRenderer": {
            "primaryContents": {
                "sectionListRenderer": {
                    "contents": [
                        {
                            "itemSectionRenderer": {
                                "contents": [
                                    {
                                        "videoRenderer": { }
                                    {
                                    },
                                        "playlistRenderer": { }
                                    {
                                        "channelRenderer": { }
                                    },
                                        "shelfRenderer": { },
                                    },
                                        "horizontalCardListRenderer": { },
                                    }
                                ]
                            "groups": [
                                {
                                    "searchFilterGroupRenderer": {
                                        "title": {
                                            "simpleText": "Upload date"
                                        },
                                        "filters": [
                                            { }
                                        ],
                              }}],
            "secondaryContents": {
                "secondarySearchContainerRenderer": {
                    "contents": [
                        {
                            "universalWatchCardRenderer": {
                                "header": {
                                    "watchCardRichHeaderRenderer": {
                                "callToAction": { },
                                "sections": [
                                    {
                                        "watchCardSectionSequenceRenderer": {
                                            "lists": [
                                                {
                                                    "verticalWatchCardListRenderer": {
                                                        "items": [
                                                            {
                                                                "watchCardCompactVideoRenderer": {
                                    ...
                                        "watchCardSectionSequenceRenderer": {
                                    ...
    "refinements": [ // lol
        "lil wayne eminem",
        "lil wayne mr carter",
        "lil wayne - she will",
        "lil wayne a milli",
        "lil wayne carter 3",
        "lil wayne - fireman",
        "lil wayne lollipop",
        "lil wayne 2021",
        "lil wayne mrs officer",
        "mirror lil wayne instrumental",
        "lil wayne mirror",
        "lil wayne - uproar",
        "mirror justin timberlake",
        "lil wayne high school",
        "lil wayne love",
        "mirror lil wayne slowed",
        "lil wayne nicki minaj",
        "lil wayne lyrics"
    ]
...

] }}}}
````

**Comment by 93null** [comment]
# Svelte Re-write

The code is sort of a disaster. I want to do it again. I'm gonna take the opportunity to try out Svelte.

- [ ] bundle ytdl
- [ ] make command to fetch results
- [ ] make command to parse results
- [ ] make command to download video
- [ ] send query from frontend
- [ ] display results in frontend
- [ ] send download request from frontend
- [ ] display download progress in frontend
- [ ] cancel download from frontend
- [ ] open finished file from frontend
- [ ] go to sleep

**Comment by 93null** [comment]
# Thoughts

## Tauri + Youtube-DL/YT-DLP
Running youtube-dl binary from app gives a python error. yt-dlp has a standalone release that doesn't require python, and seems to work fine.

## Svelte
Svelte is nice. Very nice.

## Building
Doesn't seem to work when built for release. Need to debug by building with devtools cargo.toml/tauri feature enabled.

**Comment by 93null** [comment]
# Building (cont.)

YT-DLP can't save videos to installed/bundled directory, so provide a save path as a parameter ie. `-P "~/Desktop"`
